### ISSUE TITLE
On OSx

### ISSUE THREAD

**Issue by chriskamphuis** [informagi/mmead#9]
```
>>> from mmead import get_links
>>> links = get_links('v1', 'passage', linker='rel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/data/links.py", line 7, in get_links
    return V1PassageLinksREL(verbose)
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/data/links.py", line 35, in __init__
    super().__init__(key="msmarco_v1_passage_links", verbose=verbose)
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/data/links.py", line 24, in __init__
    self.cursor = load_links(self.identifier, verbose=verbose, linker=linker)
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/util.py", line 101, in load_links
    cursor = _get_cursor()
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/util.py", line 13, in _get_cursor
    return get_connection().cursor
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/connection.py", line 12, in get_connection
    _db_connection = DBConnection(database)
  File "/Users/jimmylin/opt/anaconda3/envs/mmead/lib/python3.8/site-packages/mmead/connection.py", line 30, in __init__
    mem_bytes = os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES')
ValueError: unrecognized configuration name
```

**Comment by chriskamphuis** [comment]
fixed, but we need to make a better solution.
